name: Build, Test and Store - Part 2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build-test:
    runs-on: self-hosted

    # steps:
    #   - name: Checkout Source Code
    #     uses: actions/checkout@v6
    
    steps:
      - name: Checkout current repo (optional)
        uses: actions/checkout@v4
    
      - name: Checkout OITWorkpapers_API-Origin-Service
        uses: actions/checkout@v4
        with:
          repository: https://github.com/tr/OITWorkpapers_API-Origin-Service.git  # org/repo
          ref: main                                        # or a tag/SHA
          path: OITWorkpapers_API-Origin-Service           # folder name to place it in

  
      - name: Install Dependencies
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
  
      - name: show Versions
        run:  |
          java -version
          ./mvnw -version
  
      - name: Build Package
        run:  ./mvnw clean package
  
      - name: Test Project
        run:  ./mvnw -B test
  
      - name: Upload Artifacts
        if: always()
        uses:  actions/checkout@v4
        with: 
          name:  API-Origin-Service Artifacts
          path:  target/Surefire-reports
  
          
    
